variables:
  bundles_url: 'https://ampl.com/demo/'
  linux64_bundle_name: 'ampl.linux64.tgz'
  macos64_bundle_name: 'ampl.macos64.tgz'
  mswin64_bundle_name: 'ampl.mswin64.zip'

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: macos
    pool: {vmImage: 'macOS-10.15'}
    steps:
      - task: UsePythonVersion@0
      - bash: |
          set -ex
          python updatelib.py
          bash build.sh
          mkdir -p upload/{macos,release}
          cp rAMPL_*.tar.gz upload/macos/
          cp rAMPL_*.tar.gz upload/release/
          cp rAMPL_*.tar.gz upload/release/rAMPL.tar.gz
        displayName: Build package
      - task: PublishBuildArtifacts@1
        inputs: {artifactName: 'drop', pathtoPublish: 'upload'}

- stage: test
  displayName: 'Test'
  dependsOn: build
  jobs:
  - job: linux
    pool: {vmImage: 'Ubuntu-16.04'}
    steps:
      - task: DownloadBuildArtifacts@0
        inputs: {artifactName: 'drop', downloadPath: '.'}
      - bash: |
          cp drop/release/* .
        displayName: Copy package
      - bash: |
          sudo R --no-save -q -e "install.packages(c('Rcpp', 'testthat'), repos='http://cran.us.r-project.org')"
        displayName: Install Rcpp and testthat
      - bash: |
          sudo bash install.sh
        displayName: Install package
      - bash: |
          set -ex
          mkdir -p ampl
          cd ampl
          curl -O $BUNDLES_URL/$LINUX64_BUNDLE_NAME
          tar xzvf $LINUX64_BUNDLE_NAME
          sudo PATH="`pwd`:$PATH" R --no-save -q -e "library(testthat); test_package('rAMPL');"
        displayName: Test package
  - job: macos
    pool: {vmImage: 'macOS-10.15'}
    steps:
      - task: DownloadBuildArtifacts@0
        inputs: {artifactName: 'drop', downloadPath: '.'}
      - bash: |
          cp drop/release/* .
        displayName: Copy package
      - bash: |
          R --no-save -q -e "install.packages(c('Rcpp', 'testthat'), repos='http://cran.us.r-project.org')"
        displayName: Install Rcpp and testthat
      - bash: |
          bash install.sh
        displayName: Install package
      - bash: |
          set -ex
          mkdir -p ampl
          cd ampl
          curl -O $BUNDLES_URL/$MACOS64_BUNDLE_NAME
          tar xzvf $MACOS64_BUNDLE_NAME
          PATH="`pwd`:$PATH" R --no-save -q -e "library(testthat); test_package('rAMPL');"
        displayName: Test package
  - job: windows
    pool: {vmImage: 'windows-2019'}
    steps:
      - task: DownloadBuildArtifacts@0
        inputs: {artifactName: 'drop', downloadPath: '.'}
      - bash: |
          cp drop/release/* .
        displayName: Copy package
      - bash: |
          R --no-save -q -e "install.packages(c('Rcpp', 'testthat'), repos='http://cran.us.r-project.org')"
        displayName: Install Rcpp and testthat
      - bash: |
          # Debug the following issue on azure pipelines:
          # "C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -shared -static-libgcc -o rAMPL.dll tmp.def RcppExports.o rampl.o rcon_entity.o rcon_instance.o renvironment.o robj_entity.o robj_instance.o rparam_entity.o rset_entity.o rset_instance.o rvar_entity.o rvar_instance.o utils.o -L../inst/libs/i386 -L../inst/libs/x64 -lampl -LC:/PROGRA~1/R/R-40~1.3/bin/x64 -lR
          # /usr/bin/sh: line 8: "C:/rtools40/mingw64/bin/"g++ -std=gnu++11 : No such file or directory
          # no DLL was created
          set -ex
          grep " -shared " -R  `R RHOME`
          cat `R RHOME`/etc/x64/Makeconf
          cat `R RHOME`/etc/i386/Makeconf
          cat `R RHOME`/share/make/winshlib.mk
        displayName: Debug azure-pipelines issue
      - bash: |
          sed -i 's/\$(SHLIB_LD) -shared/c:\/rtools40\/mingw64\/bin\/g++ -shared/g' `R RHOME`/share/make/winshlib.mk
        displayName: Hack to fix azure-pipelines issue
      - bash: |
          bash install.sh
        displayName: Install package
      - bash: |
          set -ex
          mkdir -p ampl
          cd ampl
          curl -O $BUNDLES_URL/$MSWIN64_BUNDLE_NAME
          unzip $MSWIN64_BUNDLE_NAME
          PATH="`pwd`:$PATH" R --no-save -q -e "library(testthat); test_package('rAMPL');"
        displayName: Test package
