context('Test Parameter')

test_that('test parameter entity', {
  ampl <- new(AMPL)
  ampl$eval('param p = 1;')
  p <- ampl$getParameter('p')

  expect_equal(p$name(), 'p')
  expect_equal(p$toString(), 'param p = 1;')

  expect_equal(p$indexarity(), 0)
  expect_equal(p$isScalar(), TRUE)
  expect_equal(p$numInstances(), 1)
  expect_equal(length(p$getIndexingSets()), 0)
  expect_equal(p$getValues()$p, 1)
  ampl$eval('param px;')
  px <- ampl$getParameter('px')
  px$setValues(p$getValues())
  expect_equal(px$getValues()$px, 1)
  expect_equal(p$find(c()), 1)
  expect_equal(p$find(c(123)), NULL)
  expect_equal(length(p$getInstances()[[1]]), 1)

  expect_equal(p$get(c()), 1)
  expect_equal(p$value(), 1)
  expect_equal(p$isSymbolic(), FALSE)
  ampl$eval('param p2{1..10};')
  p2 <- ampl$getParameter('p2')
  ampl$eval('param p3{1..10};')
  p3 <- ampl$getParameter('p3')
  df = data.frame(index=1:10, value=15:24)
  p2$setValues(df)
  p3$setValues(p2$getValues())
  expect_equal(p3[[1]], 15)
  p3$set(2, -1)
  expect_equal(p3[[2]], -1)
  p3[[2]] <- 123
  expect_equal(p3[[2]], 123)
  expect_equal(p2[[2]], 16)
  p3[[2]] <- p2[[2]]
  expect_equal(p3[[2]], p2[[2]])
  expect_equal(p3[[2]], 16)
  expect_equal(nrow(p3$getValues()), 10)
  ampl$eval('param p4 symbolic;')
  p4 <- ampl$getParameter('p4')
  p4$set('test')
  expect_equal(p4$value(), 'test')
})
