context("Test Set")

test_that("test set entity", {
  ampl <- new(AMPL)
  ampl$eval("set s := 1..10;")
  ampl$eval("set s2 := {1..10, 1..10};")
  s <- ampl$getSet("s")
  s2 <- ampl$getSet("s2")

  expect_equal(s$name(), "s")
  expect_equal(s$toString(), "set s = 1 .. 10;")
  expect_equal(s$indexarity(), 0)
  expect_equal(s$isScalar(), TRUE)
  expect_equal(s$numInstances(), 1)
  expect_equal(length(s$getIndexingSets()), 0)
  expect_equal(length(s$xref()), 0)
  expect_equal(length(s$getValues()$s), 10)
  ampl$eval("set scopy;")
  scopy <- ampl$getSet("scopy")
  scopy$setValues(s$getValues())
  expect_equal(length(scopy$getValues()$scopy), 10)
  expect_equal(s$find(c())$name(), "s")
  expect_equal(s$find(c(123)), NULL)
  expect_equal(s$getInstances()$s$name(), "s")

  expect_equal(s$arity(), 1)
  expect_equal(s$size(), 10)
  expect_equal(s$members()[[2]][[1]], 2)
  expect_equal(s2$members()[[2]][[1]], 1)
  expect_true(s$contains(1))
  expect_true(s$contains(c(1)))
  expect_true(s2$contains(c(1, 2)))
  expect_equal(length(s$getValues()), 1)
  expect_equal(length(s2$getValues()), 2)
  ampl$eval("set s3 dimen 2;")
  s3 <- ampl$getSet("s3")
  s3$setValues(s2$getValues())
  expect_equal(length(s3$getValues()), 2)
  expect_equal(nrow(s3$getValues()), 100)
  ampl$eval("set s4;")
  s4 <- ampl$getSet("s4")
  s4$setValues(1:5)
  expect_equal(s4$size(), 5)
})

test_that("test set instance", {
  ampl <- new(AMPL)
  ampl$eval("set s := 1..10;")
  ampl$eval("set s2 := {1..10, 1..10};")
  s <- ampl$getSet("s")$get(c())
  s2 <- ampl$getSet("s2")$get(c())

  expect_equal(s$name(), "s")
  expect_equal(s$toString(), "set s;")

  # expect_equal(s$arity(), 1) # FIXME: missing in C++?
  expect_equal(s$size(), 10)
  expect_equal(s$members()[[2]][[1]], 2)
  expect_equal(s2$members()[[2]][[1]], 1)
  expect_true(s$contains(1))
  expect_true(s$contains(c(1)))
  expect_true(s2$contains(c(1, 2)))
  expect_equal(length(s$getValues()), 1)
  expect_equal(length(s2$getValues()), 2)
  ampl$eval("set s3 dimen 2;")
  s3 <- ampl$getSet("s3")$get(c())
  s3$setValues(s2$getValues())
  expect_equal(length(s3$getValues()), 2)
  expect_equal(nrow(s3$getValues()), 100)
  ampl$eval("set s4;")
  s4 <- ampl$getSet("s4")$get(c())
  s4$setValues(1:5)
  expect_equal(s4$size(), 5)
})
