context('Test Objective')

test_that('test objective entity', {
  ampl <- new(AMPL)
  ampl$eval('maximize obj: 0;')
  obj <- ampl$getObjective('obj')
  expect_equal(obj$name(), 'obj')
  expect_equal(obj$toString(), 'maximize obj: 0;')
  expect_equal(obj$value(), 0)
  expect_equal(obj$astatus(), 'in')
  expect_equal(obj$sstatus(), 'none')
  expect_equal(obj$exitcode(), -1)
  expect_equal(obj$message(), '\'?\'')
  expect_equal(obj$result(), 0)
  obj$drop()
  expect_equal(obj$astatus(), 'drop')
  obj$restore()
  expect_equal(obj$astatus(), 'in')
  expect_equal(obj$minimization(), FALSE)
  expect_equal(obj$getValues()$obj[1], 0)
})

test_that('test objective instance', {
  ampl <- new(AMPL)
  ampl$eval('maximize obj: 0;')
  obj <- ampl$getObjective('obj')$get(c())
  expect_equal(obj$name(), 'obj')
  # expect_equal(c$toString(), 'maximize obj: 0;') # FIXME: 'maximize obj:\n\t0;'?
  expect_equal(obj$value(), 0)
  expect_equal(obj$astatus(), 'in')
  expect_equal(obj$sstatus(), 'none')
  expect_equal(obj$exitcode(), -1)
  expect_equal(obj$message(), '\'?\'')
  expect_equal(obj$result(), 0)
  obj$drop()
  expect_equal(obj$astatus(), 'drop')
  obj$restore()
  expect_equal(obj$astatus(), 'in')
  expect_equal(obj$minimization(), FALSE)
})
