context('Test Variable')

test_that('test variable entity', {
  ampl <- new(AMPL)
  ampl$eval('var x;')
  x <- ampl$getVariable('x')
  expect_equal(x$name(), 'x')
  expect_equal(x$toString(), 'var x;')
  expect_equal(x$integrality(), 'C')
  expect_equal(x$astatus(), 'unused')
  x$fix(3)
  expect_equal(x$astatus(), 'fix')
  x$unfix()
  x$setValue(5)
  expect_equal(x$getValues()$x.val[1], 5)
  expect_equal(x$astatus(), 'unused')
  expect_equal(x$defeqn(), 0)
  expect_equal(x$dual(), 0)
  expect_equal(x$init(), 0)
  expect_equal(x$init0(), 0)
  expect_equal(x$lb(), -Inf)
  expect_equal(x$ub(), Inf)
  expect_equal(x$lb0(), -Inf)
  expect_equal(x$ub0(), Inf)
  expect_equal(x$lb1(), -Inf)
  expect_equal(x$ub1(), Inf)
  expect_equal(x$lb2(), -Inf)
  expect_equal(x$ub2(), Inf)
  expect_equal(x$lrc(), 0)
  expect_equal(x$urc(), 0)
  expect_equal(x$lslack(), Inf)
  expect_equal(x$uslack(), Inf)
  expect_equal(x$rc(), 0)
  expect_equal(x$slack(), Inf)
  expect_equal(x$sstatus(), 'none')
  expect_equal(x$status(), 'unused')
})

test_that('test variable instance', {
  ampl <- new(AMPL)
  ampl$eval('var x;')
  x <- ampl$getVariable('x')$get(c())
  expect_equal(x$name(), 'x')
  expect_equal(x$toString(), 'var x ;') # FIXME: unnecessary space?
  # expect_equal(x$integrality(), 'C') # FIXME: missing in C++?
  expect_equal(x$astatus(), 'unused')
  x$fix(3)
  expect_equal(x$astatus(), 'fix')
  x$unfix()
  x$setValue(5)
  # expect_equal(x$getValues()$x.val[1], 5) # FIXME: missing in C++?
  expect_equal(x$astatus(), 'unused')
  expect_equal(x$defeqn(), 0)
  expect_equal(x$dual(), 0)
  expect_equal(x$init(), 0)
  expect_equal(x$init0(), 0)
  expect_equal(x$lb(), -Inf)
  expect_equal(x$ub(), Inf)
  expect_equal(x$lb0(), -Inf)
  expect_equal(x$ub0(), Inf)
  expect_equal(x$lb1(), -Inf)
  expect_equal(x$ub1(), Inf)
  expect_equal(x$lb2(), -Inf)
  expect_equal(x$ub2(), Inf)
  expect_equal(x$lrc(), 0)
  expect_equal(x$urc(), 0)
  expect_equal(x$lslack(), Inf)
  expect_equal(x$uslack(), Inf)
  expect_equal(x$rc(), 0)
  expect_equal(x$slack(), Inf)
  expect_equal(x$sstatus(), 'none')
  expect_equal(x$status(), 'unused')
})
