context("Test Variable")

test_that("test variable entity", {
  ampl <- new(AMPL)
  ampl$eval("var x;")
  ampl$eval("var x2;")
  ampl$eval("var y{1..10};")
  ampl$eval("var y2{1..10};")
  x <- ampl$getVariable("x")
  y <- ampl$getVariable("y")
  x2 <- ampl$getVariable("x2")
  y2 <- ampl$getVariable("y2")

  expect_equal(x$name(), "x")
  expect_equal(x$toString(), "var x;")
  expect_equal(x$indexarity(), 0)
  expect_equal(y$indexarity(), 1)
  expect_equal(x$isScalar(), TRUE)
  expect_equal(y$isScalar(), FALSE)
  expect_equal(x$numInstances(), 1)
  expect_equal(y$numInstances(), 10)
  expect_equal(length(x$getIndexingSets()), 0)
  expect_equal(y$getIndexingSets(), "1 .. 10")
  expect_equal(x$getValues()$x.val, 0)
  expect_equal(x$getValues("dual")$x.dual, 0)
  x2$setValues(x$getValues())
  y2$setValues(y$getValues())
  expect_equal(x$find(c())$name(), "x")
  expect_equal(x$find(c(123)), NULL)
  expect_equal(y$find(c()), NULL)
  expect_equal(y$find(c(1))$name(), "y[1]")
  expect_equal(x$getInstances()$x$name(), "x")
  expect_equal(y$getInstances()[["y[3]"]]$name(), "y[3]")

  expect_equal(x$value(), 0)
  expect_equal(x$integrality(), "C")
  expect_equal(x$astatus(), "unused")
  x$fix(3)
  expect_equal(x$astatus(), "fix")
  x$unfix()
  x$setValue(5)
  expect_equal(x$getValues()$x.val[1], 5)
  expect_equal(x$astatus(), "unused")
  expect_equal(x$defeqn(), 0)
  expect_equal(x$dual(), 0)
  expect_equal(x$init(), 0)
  expect_equal(x$init0(), 0)
  expect_equal(x$lb(), -Inf)
  expect_equal(x$ub(), Inf)
  expect_equal(x$lb0(), -Inf)
  expect_equal(x$ub0(), Inf)
  expect_equal(x$lb1(), -Inf)
  expect_equal(x$ub1(), Inf)
  expect_equal(x$lb2(), -Inf)
  expect_equal(x$ub2(), Inf)
  expect_equal(x$lrc(), 0)
  expect_equal(x$urc(), 0)
  expect_equal(x$lslack(), Inf)
  expect_equal(x$uslack(), Inf)
  expect_equal(x$rc(), 0)
  expect_equal(x$slack(), Inf)
  expect_equal(x$sstatus(), "none")
  expect_equal(x$status(), "unused")
})

test_that("test variable instance", {
  ampl <- new(AMPL)
  ampl$eval("var x;")
  x <- ampl$getVariable("x")$get(c())

  expect_equal(x$name(), "x")
  expect_equal(x$toString(), "var x ;") # FIXME: unnecessary space?

  # expect_equal(x$integrality(), "C") # FIXME: missing in C++?
  expect_equal(x$value(), 0)
  expect_equal(x$astatus(), "unused")
  x$fix(3)
  expect_equal(x$astatus(), "fix")
  x$unfix()
  x$setValue(5)
  # expect_equal(x$getValues()$x.val[1], 5) # FIXME: missing in C++?
  expect_equal(x$astatus(), "unused")
  expect_equal(x$defeqn(), 0)
  expect_equal(x$dual(), 0)
  expect_equal(x$init(), 0)
  expect_equal(x$init0(), 0)
  expect_equal(x$lb(), -Inf)
  expect_equal(x$ub(), Inf)
  expect_equal(x$lb0(), -Inf)
  expect_equal(x$ub0(), Inf)
  expect_equal(x$lb1(), -Inf)
  expect_equal(x$ub1(), Inf)
  expect_equal(x$lb2(), -Inf)
  expect_equal(x$ub2(), Inf)
  expect_equal(x$lrc(), 0)
  expect_equal(x$urc(), 0)
  expect_equal(x$lslack(), Inf)
  expect_equal(x$uslack(), Inf)
  expect_equal(x$rc(), 0)
  expect_equal(x$slack(), Inf)
  expect_equal(x$sstatus(), "none")
  expect_equal(x$status(), "unused")
})
