context("Test Environment")

test_that("test environment initialization", {
  env = new(Environment, "binary_directory")
  expect_equal("binary_directory", env$getBinDir())
  env = new(Environment, "binary_directory", "binary_name")
  expect_equal("binary_directory", env$getBinDir())
  expect_equal("binary_name", env$getBinName())
  env$setBinDir("binary_directory_2")
  expect_equal("binary_directory_2", env$getBinDir())
  env$setBinName("binary_name_2")
  expect_equal("binary_name_2", env$getBinName())
})

test_that("test environment", {
  env1 <- new(Environment)
  ampl <- new(AMPL, env1)
  env2 <- new(Environment, "path_to_binary")
  expect_equal(env2$getBinDir(), "path_to_binary")
  expect_error(new(AMPL, env2))
  env1$setBinDir("path_to_binary")
  expect_equal(env1$getBinDir(), "path_to_binary")
  expect_true(is.na(env1$get("x")))
  env1$put("env_var1", "env_var1_value")
  expect_equal(env1$get("env_var1"), "env_var1_value")
  expect_true(grepl("env_var1_value", env1$toString()))
  env1$put("env_var1", "other_value")
  expect_equal(env1$get("env_var1"), "other_value")
  expect_equal(env1$list()$env_var1, "other_value")
})
