context("Test Constraint")

test_that("test constraint entity", {
  ampl <- new(AMPL)
  ampl$eval("var x;");
  ampl$eval("s.t. c: x = 0;")
  c <- ampl$getConstraint("c")

  expect_equal(c$name(), "c")
  expect_equal(c$toString(), "subject to c: x == 0;")
  expect_equal(c$indexarity(), 0)
  expect_equal(c$isScalar(), TRUE)
  expect_equal(c$numInstances(), 1)
  expect_equal(length(c$getIndexingSets()), 0)
  expect_equal(c$getValues()$c.dual, 0)
  expect_equal(c$getValues("ub")$c.ub, 0)
  ampl$eval("s.t. c2: x = 0;")
  c2 <- ampl$getConstraint("c2")
  c2$setValues(c$getValues())
  expect_equal(c$find(c())$name(), "c")
  expect_equal(c$find(c(123)), NULL)
  expect_equal(c$getInstances()$c$name(), "c")

  expect_equal(c$isLogical(), FALSE)
  expect_equal(c$astatus(), "pre")
  c$drop()
  expect_equal(c$astatus(), "drop")
  c$restore()
  expect_equal(c$astatus(), "pre")
  expect_equal(c$body(), 0)
  expect_equal(c$astatus(), "pre")
  expect_equal(c$defvar(), 0)
  expect_equal(c$dinit(), 0)
  expect_equal(c$dinit0(), 0)
  expect_equal(c$dual(), 0)
  expect_equal(c$lb(), 0)
  expect_equal(c$ub(), 0)
  expect_equal(c$lbs(), 0)
  expect_equal(c$ubs(), 0)
  expect_equal(c$ldual(), 0)
  expect_equal(c$udual(), 0)
  expect_equal(c$lslack(), 0)
  expect_equal(c$uslack(), 0)
  expect_equal(c$slack(), 0)
  expect_equal(c$sstatus(), "none")
  expect_equal(c$status(), "pre")
  c$setDual(5)
  expect_error(c$val())
  expect_equal(c$getValues()$c.dual[1], 0)
})

test_that("test constraint instance", {
  ampl <- new(AMPL)
  ampl$eval("var x;");
  ampl$eval("s.t. c: x = 0;")
  c <- ampl$getConstraint("c")$get(c())

  expect_equal(c$name(), "c")
  # expect_equal(c$toString(), "subject to c: x == 0;") # FIXME: "subject to c:\n\tx = 0;"?

  # expect_equal(c$isLogical(), FALSE) # FIXME: missing in C++?
  expect_equal(c$astatus(), "pre")
  c$drop()
  expect_equal(c$astatus(), "drop")
  c$restore()
  expect_equal(c$astatus(), "pre")
  expect_equal(c$body(), 0)
  expect_equal(c$astatus(), "pre")
  expect_equal(c$defvar(), 0)
  expect_equal(c$dinit(), 0)
  expect_equal(c$dinit0(), 0)
  expect_equal(c$dual(), 0)
  expect_equal(c$lb(), 0)
  expect_equal(c$ub(), 0)
  expect_equal(c$lbs(), 0)
  expect_equal(c$ubs(), 0)
  expect_equal(c$ldual(), 0)
  expect_equal(c$udual(), 0)
  expect_equal(c$lslack(), 0)
  expect_equal(c$uslack(), 0)
  expect_equal(c$slack(), 0)
  expect_equal(c$sstatus(), "none")
  expect_equal(c$status(), "pre")
  c$setDual(5)
  expect_error(c$val())
})
