// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_rampl();
RcppExport SEXP _rcpp_module_boot_rcon_entity();
RcppExport SEXP _rcpp_module_boot_rcon_instance();
RcppExport SEXP _rcpp_module_boot_renvironment();
RcppExport SEXP _rcpp_module_boot_robj_entity();
RcppExport SEXP _rcpp_module_boot_robj_instance();
RcppExport SEXP _rcpp_module_boot_rparam_entity();
RcppExport SEXP _rcpp_module_boot_rset_entity();
RcppExport SEXP _rcpp_module_boot_rset_instance();
RcppExport SEXP _rcpp_module_boot_rvar_entity();
RcppExport SEXP _rcpp_module_boot_rvar_instance();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_rampl", (DL_FUNC) &_rcpp_module_boot_rampl, 0},
    {"_rcpp_module_boot_rcon_entity", (DL_FUNC) &_rcpp_module_boot_rcon_entity, 0},
    {"_rcpp_module_boot_rcon_instance", (DL_FUNC) &_rcpp_module_boot_rcon_instance, 0},
    {"_rcpp_module_boot_renvironment", (DL_FUNC) &_rcpp_module_boot_renvironment, 0},
    {"_rcpp_module_boot_robj_entity", (DL_FUNC) &_rcpp_module_boot_robj_entity, 0},
    {"_rcpp_module_boot_robj_instance", (DL_FUNC) &_rcpp_module_boot_robj_instance, 0},
    {"_rcpp_module_boot_rparam_entity", (DL_FUNC) &_rcpp_module_boot_rparam_entity, 0},
    {"_rcpp_module_boot_rset_entity", (DL_FUNC) &_rcpp_module_boot_rset_entity, 0},
    {"_rcpp_module_boot_rset_instance", (DL_FUNC) &_rcpp_module_boot_rset_instance, 0},
    {"_rcpp_module_boot_rvar_entity", (DL_FUNC) &_rcpp_module_boot_rvar_entity, 0},
    {"_rcpp_module_boot_rvar_instance", (DL_FUNC) &_rcpp_module_boot_rvar_instance, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rAMPL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
