// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_ampl_module();
RcppExport SEXP _rcpp_module_boot_environment_module();
RcppExport SEXP _rcpp_module_boot_parameter_module();
RcppExport SEXP _rcpp_module_boot_rcon_entity();
RcppExport SEXP _rcpp_module_boot_rcon_instance();
RcppExport SEXP _rcpp_module_boot_robj_entity();
RcppExport SEXP _rcpp_module_boot_robj_instance();
RcppExport SEXP _rcpp_module_boot_rvarentity();
RcppExport SEXP _rcpp_module_boot_rvarinstance();
RcppExport SEXP _rcpp_module_boot_set_module();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_ampl_module", (DL_FUNC) &_rcpp_module_boot_ampl_module, 0},
    {"_rcpp_module_boot_environment_module", (DL_FUNC) &_rcpp_module_boot_environment_module, 0},
    {"_rcpp_module_boot_parameter_module", (DL_FUNC) &_rcpp_module_boot_parameter_module, 0},
    {"_rcpp_module_boot_rcon_entity", (DL_FUNC) &_rcpp_module_boot_rcon_entity, 0},
    {"_rcpp_module_boot_rcon_instance", (DL_FUNC) &_rcpp_module_boot_rcon_instance, 0},
    {"_rcpp_module_boot_robj_entity", (DL_FUNC) &_rcpp_module_boot_robj_entity, 0},
    {"_rcpp_module_boot_robj_instance", (DL_FUNC) &_rcpp_module_boot_robj_instance, 0},
    {"_rcpp_module_boot_rvarentity", (DL_FUNC) &_rcpp_module_boot_rvarentity, 0},
    {"_rcpp_module_boot_rvarinstance", (DL_FUNC) &_rcpp_module_boot_rvarinstance, 0},
    {"_rcpp_module_boot_set_module", (DL_FUNC) &_rcpp_module_boot_set_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rAMPL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
